### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by toastyy00** [frankrichardhall/T3rn-Executor-bot#1]
is this script for executor or auto bridge asset?

**Comment by frankrichardhall** [comment]
Bridge Asset

**Comment by toastyy00** [comment]
but in it there is no bridge function, only run executor

**Comment by frankrichardhall** [comment]
Thank you for informing me and for fixing the issue. For the T3rn Airdrop Bot, you can find it here: [T3rn Airdrop Bot](https://github.com/frankrichardhall/T3rn-Airdrop-bot).
